[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "SRL"
version = "0.0.1"
authors = [
  {name="Filipo STUDZINSKI PEROTTO", email="filipo.perotto@onera.fr"},
  {name="Aymane OUHABI", email="aymane.ouhabi@onera.fr"},
  {name="Melvine NARGEOT", email="melvine.nargeot@onera.fr"},
]
description = "Safe and Survival Reinforcement Learning"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/fsperotto/srl"
"Bug Tracker" = "https://github.com/fsperotto/srl/issues"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["srl", "srl.mab", "srl.gr", "srl.mdp"]